create:
  #!/usr/bin/env bash
  cat <<EOF | kind create cluster --config -
  kind: Cluster
  apiVersion: kind.x-k8s.io/v1alpha4
  name: gitlab
  nodes:
  - role: control-plane
  - role: worker
  - role: worker
  EOF

# delete kind cluster
delete:
  kind delete cluster --name gitlab
